# Generated by Django 5.1.3 on 2024-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=16, unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=250)),
                ('pp', models.ImageField(blank=True, upload_to='profile_pic/')),
            ],
        ),
    ]
