# Generated by Django 5.1.3 on 2025-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_score_game_score1_game_score2'),
        ('users', '0009_user_is_stud_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='players', to='game.game'),
        ),
    ]
