# Generated by Django 5.1.3 on 2025-01-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_player1_paddle_x_game_player1_paddle_y_and_more'),
        ('users', '0010_remove_user_is_stud_remove_user_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='players', to='game.game'),
        ),
    ]
