# Generated by Django 5.1.3 on 2025-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_stud',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
