# Generated by Django 5.1.3 on 2025-01-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_verified_confirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
