# Generated by Django 5.1.3 on 2025-02-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_last_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_verified',
            field=models.BooleanField(default=False),
        ),
    ]
