# Generated by Django 5.1.3 on 2025-02-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_last_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_waiting',
            field=models.BooleanField(default=False),
        ),
    ]
