# Generated by Django 5.1.3 on 2025-02-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_enable_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
