# Generated by Django 5.1.3 on 2025-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_waiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_waiting',
            field=models.IntegerField(default=0),
        ),
    ]
