
# Generated by Django 5.1.3 on 2025-02-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_ip_user'),
        ('users', '0015_alter_user_is_waiting'),
    ]

    operations = [
    ]
