# Generated by Django 5.1.3 on 2025-02-26 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_0014_user_ip_user_0015_alter_user_is_waiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_user',
            field=models.ManyToManyField(related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
