# Generated by Django 5.1.3 on 2025-02-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elo',
            field=models.IntegerField(default=100),
        ),
    ]
