# Generated by Django 5.1.3 on 2025-02-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_blockeduser_user_blocked_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUser',
        ),
    ]
