# Generated by Django 5.1.3 on 2025-03-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_elo'),
        ('users', '0020_alter_user_blocked_user'),
    ]

    operations = [
    ]
