# Generated by Django 5.1.3 on 2025-03-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_merge_0018_user_elo_0020_alter_user_blocked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='elo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_verified',
        ),
    ]
