# Generated by Django 5.1.3 on 2025-03-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_is_stud_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
