services:
  nginx:
    environment:
      - WATCHPACK_POLLING=true
    env_file: .env
    container_name: nginx
    build: nginx/
    depends_on:
      - react
    volumes:
      - project:/home/
    networks:
      - tdc
    image: nginx
    ports:
      - 8089:443
    restart: unless-stopped
      
  db:
    environment:
      - WATCHPACK_POLLING=true
    container_name: db
    image: postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - tdc
    volumes:
      - db:/home/db

  react:
    environment:
      - WATCHPACK_POLLING=true
    container_name: react
    image: front
    restart: unless-stopped
    env_file: .env
    build: ./frontend/
    volumes:
      - project:/home/
    depends_on:
      - db
      - django
    ports:
      - 3000:3000
    networks:
      - tdc

  django: 
    container_name: django
    image: django
    restart: unless-stopped
    env_file: .env
    build: ./backend/
    volumes:
      - project:/home/
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    networks: 
      - tdc
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WATCHPACK_POLLING=true
  
  redis:
    environment:
      - WATCHPACK_POLLING=true
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0"]
    networks:
      - tdc


volumes:
  project:
    driver: local
    driver_opts:
        type: none
        o: 'bind'
        device: .
  db:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: ./db

networks:
  tdc:
    name: tdc
    driver: bridge