services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 5432:5432
    networks:
      - tdc
    volumes:
      - db:/home/db

  react:
    container_name: react
    image: front
    restart: unless-stopped
    build:
      context: ./frontend/
    environment:
      - WATCHPACK_POLLING=true
      - HTTPS=true
      - PORT=3000
    volumes:
      - ./certs:/home/certs
    depends_on:
      - db
      - django
    ports:
      - 3000:3000
    networks:
      - tdc

  django: 
    container_name: django
    image: django
    restart: unless-stopped
    env_file: .env
    build: ./backend/
    volumes:
      - project:/home/
      - ./certs:/home/certs
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    networks: 
      - tdc
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WATCHPACK_POLLING=true
  
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "6000:6000"
    command: ["redis-server", "--bind", "0.0.0.0"]
    networks:
      - tdc

volumes:
  project:
    driver: local
    driver_opts:
        type: none
        o: 'bind'
        device: .
  db:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: ./db

networks:
  tdc:
    name: tdc
    driver: bridge