# Generated by Django 5.1.3 on 2024-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
