# Generated by Django 5.1.3 on 2024-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_loser_alter_game_player1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='score',
            new_name='score1',
        ),
        migrations.AddField(
            model_name='game',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
