# Generated by Django 5.1.3 on 2024-12-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_score_game_score1_game_score2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_paddle_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_paddle_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_paddle_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_paddle_y',
            field=models.IntegerField(default=0),
        ),
    ]
