# Generated by Django 5.1.3 on 2025-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_score1_game_score_player_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
        migrations.AddField(
            model_name='game',
            name='timeMinutes',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='game',
            name='timeSeconds',
            field=models.IntegerField(default=59),
        ),
    ]
