# Generated by Django 5.1.3 on 2025-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('started', 'Game Started'), ('finished', 'Game Finished'), ('ready', 'Ready waiting to start')], default='waiting', max_length=10),
        ),
    ]
