# Generated by Django 5.1.3 on 2025-02-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_player1ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1Ready',
            field=models.IntegerField(default=0),
        ),
    ]
