# Generated by Django 5.1.3 on 2025-02-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_game_player1ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1Ready',
            field=models.BooleanField(default=False),
        ),
    ]
