# Generated by Django 5.1.3 on 2025-02-21 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_game_player1ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1Ready',
        ),
        migrations.AddField(
            model_name='game',
            name='timeMinutesScoreP1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='game',
            name='timeMinutesScoreP2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='game',
            name='timeSecondsScoreP1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='game',
            name='timeSecondsScoreP2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
