# Generated by Django 5.1.3 on 2025-02-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_game_player1ready_game_timeminutesscorep1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='timeMinutesScoreP1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='timeMinutesScoreP2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='timeSecondsScoreP1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='timeSecondsScoreP2',
        ),
    ]
