# Generated by Django 5.1.3 on 2025-02-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_remove_game_timeminutesscorep1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('timeMaxMinutes', models.IntegerField(default=0)),
                ('timeMaxSeconds', models.IntegerField(default=0)),
                ('scoreMax', models.IntegerField(default=0)),
                ('player1', models.CharField(blank=True, max_length=255)),
                ('player2', models.CharField(blank=True, max_length=255)),
                ('player3', models.CharField(blank=True, max_length=255)),
                ('player4', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
