# Generated by Django 5.1.3 on 2025-02-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gamesTournament',
            field=models.ManyToManyField(blank=True, related_name='tournament_players', to='game.game'),
        ),
    ]
