# Generated by Django 5.1.3 on 2025-02-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_tournament_gamestournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('started', 'Tournament Started'), ('finished', 'Tournament Finished'), ('ready', 'Ready waiting to start')], default='waiting', max_length=10),
        ),
    ]
