# Generated by Django 5.1.3 on 2025-02-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='size',
            field=models.IntegerField(default=4),
        ),
    ]
