# Generated by Django 5.1.3 on 2025-02-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_tournament_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='elo_Player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='elo_Player2',
            field=models.IntegerField(default=0),
        ),
    ]
