# Generated by Django 5.1.3 on 2025-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_game_elo_player1_game_elo_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isInTournament',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
