# Generated by Django 5.1.3 on 2025-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_game_isintournament_tournament_winner1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players_connected',
            field=models.IntegerField(default=0),
        ),
    ]
