# Generated by Django 5.1.3 on 2025-03-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_tournament_players_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='scoreMax',
            field=models.IntegerField(default=11),
        ),
    ]
