# Generated by Django 5.1.3 on 2025-03-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_tournament_winner1_alter_tournament_winner2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='winner1',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner2',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
