# Generated by Django 5.1.3 on 2025-03-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_tournament_winner1_alter_tournament_winner2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner_final',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
