# Generated by Django 5.1.3 on 2025-03-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_tournament_winner_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
