# Generated by Django 5.1.3 on 2025-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='first',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fourth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
