# Generated by Django 5.1.3 on 2025-03-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_tournament_first_tournament_fourth_tournament_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tie',
            field=models.BooleanField(default=True),
        ),
    ]
