# Generated by Django 5.1.3 on 2025-03-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_tournament_tie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tie',
            field=models.BooleanField(default=False),
        ),
    ]
