# Generated by Django 5.1.3 on 2025-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_alter_tournament_tie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='scoreMax',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='size',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='timeMaxMinutes',
            field=models.IntegerField(default=3),
        ),
    ]
