# Generated by Django 5.1.3 on 2025-03-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_alter_game_status_alter_tournament_scoremax_and_more'),
        ('game', '0032_alter_tournament_scoremax_alter_tournament_size_and_more'),
    ]

    operations = [
    ]
