# Generated by Django 5.1.3 on 2025-03-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_merge_20250307_1149'),
        ('game', '0033_merge_20250307_1434'),
    ]

    operations = [
    ]
