# Generated by Django 5.1.3 on 2025-03-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_alter_tournament_first_alter_tournament_fourth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='first',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='fourth',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='second',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='third',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
