# Generated by Django 5.1.3 on 2025-03-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_alter_tournament_first_alter_tournament_fourth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='isPlayer1Connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='isPlayer2Connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='isPlayer3Connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='isPlayer4Connected',
            field=models.BooleanField(default=False),
        ),
    ]
