# Generated by Django 5.1.3 on 2025-03-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_tournament_isplayer1connected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='isPlayer1Connected',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='isPlayer2Connected',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='isPlayer3Connected',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='isPlayer4Connected',
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
