# Generated by Django 5.1.3 on 2025-03-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_merge_20250307_1456'),
        ('game', '0037_remove_tournament_isplayer1connected_and_more'),
    ]

    operations = [
    ]
