# Generated by Django 5.1.3 on 2025-03-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_merge_20250308_1649'),
        ('game', '0038_merge_20250308_1857'),
    ]

    operations = [
    ]
