# Generated by Django 5.1.3 on 2025-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_merge_20250308_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='IA',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('started', 'Game Started'), ('finished', 'Game Finished'), ('ready', 'Ready waiting to start'), ('aborted', 'One player leave the game')], default='waiting', max_length=10),
        ),
    ]
