# Generated by Django 5.1.3 on 2025-03-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_game_ia_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('started', 'Tournament Started'), ('finished', 'Tournament Finished'), ('ready', 'Ready waiting to start'), ('aborted', 'Tournament is aborted')], default='waiting', max_length=10),
        ),
    ]
