# Generated by Django 5.1.3 on 2025-03-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_alter_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='player1co',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player2co',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player3co',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player4co',
            field=models.BooleanField(default=False),
        ),
    ]
