# Generated by Django 5.1.3 on 2025-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_tournament_player1co_tournament_player2co_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('started', 'Tournament Started'), ('finished', 'Tournament Finished'), ('ready', 'Ready waiting to start'), ('aborted', 'Tournament is aborted'), ('in_Game', 'Games are started'), ('timer', 'Timer is started')], default='waiting', max_length=10),
        ),
    ]
