# Generated by Django 5.1.3 on 2024-12-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0005_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='livechat.room'),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
