# Generated by Django 5.1.3 on 2024-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0006_alter_message_room_delete_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='default_room', max_length=255, unique=True),
        ),
    ]
