# Generated by Django 5.1.3 on 2025-02-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0010_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
