# Generated by Django 5.1.3 on 2025-02-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0012_room_nb_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='room',
            name='nb_users',
        ),
    ]
