# Generated by Django 5.1.3 on 2025-02-14 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0013_remove_room_limit_remove_room_nb_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms_createur', to=settings.AUTH_USER_MODEL)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms_invite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
