# Generated by Django 5.1.3 on 2025-02-14 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0014_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='accepte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='creation2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
