# Generated by Django 5.1.3 on 2025-02-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0015_directmessage_accepte_directmessage_creation2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='creation2',
            new_name='creation',
        ),
    ]
