# Generated by Django 5.1.3 on 2025-02-17 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0016_rename_creation2_directmessage_creation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invitation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='invited_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
