# Generated by Django 5.1.3 on 2025-02-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0018_remove_room_invited_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dm',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='invitation_required',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
