# Generated by Django 5.1.3 on 2025-02-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0019_room_dm_alter_room_invitation_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='invitation_required',
            field=models.BooleanField(default=False),
        ),
    ]
