# Generated by Django 5.1.3 on 2025-02-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0020_alter_room_invitation_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='invitation_required',
        ),
        migrations.AlterField(
            model_name='room',
            name='dm',
            field=models.BooleanField(default=False),
        ),
    ]
