# Generated by Django 5.1.3 on 2025-02-25 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0022_blockeduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='blocker',
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='blocked',
            field=models.ManyToManyField(related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='blocker',
            field=models.ManyToManyField(related_name='blocking', to=settings.AUTH_USER_MODEL),
        ),
    ]
