# Generated by Django 5.1.3 on 2025-02-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0024_remove_blockeduser_blocked_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUser',
        ),
    ]
