# Generated by Django 5.1.3 on 2025-03-07 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0028_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message="Nom d'utilisateur invalide", regex='^[0-9a-zA-Z]+$')]),
        ),
    ]
