# Generated by Django 5.1.3 on 2025-03-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0030_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='password',
        ),
    ]
