# Generated by Django 5.1.3 on 2024-11-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendrequest_from_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
